#!/usr/bin/env bash
# Butterfly-farm scaling probe: how do LUT/FF/DSP scale when d butterfly
# lanes (each with its own twiddle ROM) are instantiated side by side, for
# the reference (Barrett, 3 DSP/lane, full tf_ROM) vs the proposed
# (K-RED, 1 DSP/lane, psi-fold tf_rom_fold)?  Backs docs/scaling.md.
#
# This is a LANE-ARRAY probe, deliberately without the banked memory
# network / AGU of a full d-lane core: it measures how the arithmetic
# scales and where each variant hits the device's DSP/LUT wall.
#
# Area sweep (yosys synth_xilinx):
#   nix shell nixpkgs#yosys --command fpga/scale_sweep.sh
# Optional post-route Fmax points (openXC7; slow, ~10-40 min each):
#   DO_PNR=1 NP=<nextpnr-xilinx> CHIPDB=<xc7a100tcsg324.bin> fpga/scale_sweep.sh
set -euo pipefail
cd "$(dirname "$0")/.."
RTL=cfntt_ref/hardware_code_radix-2
YOSYS=${YOSYS:-yosys}
OUT=${OUT:-/tmp/scale_sweep}; mkdir -p "$OUT"

KRED_SRC="kred-butterfly/compact_bf_v2.v kred-butterfly/modular_mul_kred.v \
  psi-fold-rom/tf_rom_fold.v $RTL/modular_add.v $RTL/modular_substraction.v \
  $RTL/modular_half.v $RTL/common_lib.v"
REF_SRC="$RTL/compact_bf.v $RTL/modular_mul.v $RTL/tf_ROM.v \
  $RTL/modular_add.v $RTL/modular_substraction.v $RTL/common_lib.v"

gen_farm() { # kind d -> $OUT/farm_<kind>_<d>.v  (self-wrapped: clk/serial io)
  local kind=$1 d=$2 bf rom
  if [ "$kind" = kred ]; then bf=compact_bf_v2; rom=tf_rom_fold
  else bf=compact_bf; rom=tf_ROM; fi
  python3 - "$kind" "$d" "$bf" "$rom" > "$OUT/farm_${kind}_${d}.v" <<'PY'
import sys
kind, d, bf, rom = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
IB = 38 * d + 1          # per lane: u14 v14 addr10; +1 shared sel
OB = 28 * d
print(f"// GENERATED by scale_sweep.sh: {d}-lane {kind} butterfly farm")
print(f"module farm (input clk, input serial_in, output serial_out);")
print(f"  reg [{IB-1}:0] ish;")
print(f"  always @(posedge clk) ish <= {{ish[{IB-2}:0], serial_in}};")
print(f"  wire sel = ish[{IB-1}];")
print(f"  wire [{OB-1}:0] ow;")
for i in range(d):
    b = 38 * i
    print(f"  wire [13:0] w{i};")
    print(f"  {rom} rom{i} (.clk(clk), .A(ish[{b+37}:{b+28}]), .REN(1'b1), .Q(w{i}));")
    print(f"  {bf} bf{i} (.clk(clk), .rst(1'b0), .sel(sel),")
    print(f"    .u(ish[{b+27}:{b+14}]), .v(ish[{b+13}:{b}]), .w(w{i}),")
    print(f"    .bf_upper(ow[{28*i+27}:{28*i+14}]), .bf_lower(ow[{28*i+13}:{28*i}]));")
print(f"  reg [{OB-1}:0] osh;")
print(f"  reg [{d-1}:0] xr1;")
print(f"  reg xr2;")
print(f"  always @(posedge clk) begin")
print(f"    osh <= ow;")
# pipeline the XOR reduce so the harness never owns the critical path:
# per-lane 28-bit XOR, then a registered d-bit XOR, then the pin
for i in range(d):
    print(f"    xr1[{i}] <= ^osh[{28*i+27}:{28*i}];")
print(f"    xr2 <= ^xr1;")
print(f"  end")
print(f"  assign serial_out = xr2;")
print(f"endmodule")
PY
}

synth_stat() { # kind d srcs...
  local kind=$1 d=$2; shift 2
  gen_farm "$kind" "$d"
  local reads="" tmp="$OUT/stat_${kind}_${d}.txt"
  for f in "$@" "$OUT/farm_${kind}_${d}.v"; do reads="$reads read_verilog $f;"; done
  $YOSYS -p "$reads synth_xilinx -flatten -top farm; tee -o $tmp stat" >/dev/null 2>&1
  awk -v K="$kind" -v D="$d" '
    /^ *[0-9]+ +LUT[1-6]/ {lut+=$1}
    /^ *[0-9]+ +FD(CE|RE|PE|SE)/ {ff+=$1}
    /^ *[0-9]+ +DSP48E1/ {dsp+=$1}
    /^ *[0-9]+ +RAMB(18|36)E1/ {bram+=$1}
    /^ *[0-9]+ +CARRY4/ {carry+=$1}
    END {printf "%-6s d=%-4d LUT=%-6d FF=%-6d DSP=%-4d BRAM=%-3d CARRY4=%-5d\n",
         K, D, lut, ff, dsp, bram, carry}
  ' "$tmp"
}

if [ "${SKIP_AREA:-0}" != 1 ]; then
  echo "== area sweep (yosys synth_xilinx, Artix-7 primitives) =="
  for d in 16 64 128 240; do synth_stat kred $d $KRED_SRC; done
  for d in 16 64 80;      do synth_stat ref  $d $REF_SRC;  done
fi

if [ "${DO_PNR:-0}" = 1 ]; then
  : "${NP:?}" "${CHIPDB:?}"
  # Which points to place-and-route, as "kind:d" pairs.  Note ref:64
  # (192/240 DSP = 80% DSP utilization) did NOT converge in 15 h of
  # nextpnr placement in our runs — dense DSP placement is hard for the
  # open placer — hence ref is probed at d=32.
  PNR_SET=${PNR_SET:-"kred:32 ref:32 kred:64 kred:128"}
  echo "== post-route Fmax points (xc7a100t, 1 seed, target 2.0 ns) =="
  pnr() { # kind d srcs...
    local kind=$1 d=$2; shift 2
    gen_farm "$kind" "$d"
    local reads=""
    for f in "$@" "$OUT/farm_${kind}_${d}.v"; do reads="$reads read_verilog $f;"; done
    $YOSYS -p "$reads synth_xilinx -flatten -top farm; delete t:\$scopeinfo; \
      write_json $OUT/farm_${kind}_${d}.json" >/dev/null 2>&1
    { echo "set_property IOSTANDARD LVCMOS33 [get_ports {clk}]"
      echo "set_property IOSTANDARD LVCMOS33 [get_ports {serial_in}]"
      echo "set_property IOSTANDARD LVCMOS33 [get_ports {serial_out}]"
      echo "create_clock -period 2.0 -name clk [get_ports clk]"; } > "$OUT/c.xdc"
    local f log="$OUT/pnr_${kind}_${d}.log"
    "$NP" --chipdb "$CHIPDB" --seed 1 --xdc "$OUT/c.xdc" \
        --json "$OUT/farm_${kind}_${d}.json" > "$log" 2>&1 || true
    f=$(grep -oE "Max frequency for clock.*: [0-9.]+ MHz" "$log" \
        | grep -oE "[0-9.]+" | tail -1 || echo FAIL)
    printf "%-6s d=%-4d Fmax=%s MHz  (log: %s)\n" "$kind" "$d" "${f:-FAIL}" "$log"
  }
  for pt in $PNR_SET; do
    case $pt in
      kred:*) pnr kred "${pt#kred:}" $KRED_SRC ;;
      ref:*)  pnr ref  "${pt#ref:}"  $REF_SRC  ;;
    esac
  done
fi
